language: node_js
node_js:
  - 6

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle

before_install:
  - npm set progress=false

install:
  - bundle install
  - npm install

before_script:
  - npm install gulp-cli -g

script:
  - gulp build

# Resolve dpl gem issue
# https://github.com/travis-ci/travis-ci/issues/5072
before_deploy:
  - export PATH="$PATH:$HOME/.rvm/bin"

deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy-production
  on:
    branch: master
