language: node_js
node_js:
  - 4

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle

before_install:
  - rvm install 2.2.2
  - npm set progress=false
  - echo -e "machine github.com\n  login ${GH_TOKEN}" >> ~/.netrc
  - git remote set-url origin "https://${GH_TOKEN}@github.com/helpscout/styleguide.git"
  - git config --global user.name "ItsJonQ"
  - git config --global user.email "itsjonq@gmail.com"
  - git config --global url.https://github.com/.insteadOf git://github.com/

install:
  - bundle install
  - npm install

before_script:
  - npm install gulp-cli -g
  - npm install bower -g
  - bower login -t $GH_TOKEN
  - bower install

script:
  - gulp build

deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy-production
  on:
    branch: master
