language: ruby
rvm:
  - 2.2.3

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 6.10.3
  - nvm use 6.10.3
  - npm set progress=false
  - echo -e "machine github.com\n login ${GH_TOKEN}" >> ~/.netrc
  - git remote set-url origin "https://${GH_TOKEN}@github.com/helpscout/seed.git"
  - git config --global user.name "ItsJonQ"
  - git config --global user.email "itsjonq@gmail.com"
  - git config --global url.https://github.com/.insteadOf git://github.com/

install:
  - bundle install
  - npm install

before_script:
  - npm rebuild node-sass --force
  - npm install gulp-cli -g

script:
  - gulp build

# Resolve dpl gem issue
# https://github.com/travis-ci/travis-ci/issues/5072
before_deploy:
  - export PATH="$PATH:$HOME/.rvm/bin"

deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy-production
  on:
    branch: master
